CREATE TABLE bills (
	packageId varchar(100) NOT NULL,
	title mediumtext,
	shortTitle mediumtext,
	collectionCode varchar(100),
	collectionName varchar(150),
	category varchar(100),
	dateIssued date,
	detailsLink mediumtext,
	download mediumtext,
	related mediumtext,
	branch varchar(100),
	pages int,
	governmentAuthor1 mediumtext,
	governmentAuthor2 mediumtext,
	suDocClassNumber varchar(100),
	billType varchar(20),
	congress int,
	originChamber varchar(50),
	currentChamber varchar(50),
	docSession int,
	billNumber int,
	billVersion varchar(100),
	isAppropriation boolean,
	isPrivate boolean,
	publisher varchar(255),
	committees mediumtext,
	members mediumtext,
	otherIdentifier mediumtext,
	docReferences mediumtext,
	lastModified datetime,
	PRIMARY KEY(packageId)
);